openapi: 3.0.0
info:
  title: Physical AI & Humanoid Robotics Textbook RAG Chatbot API
  version: 1.0.0
description: API for the Retrieval-Augmented Generation (RAG) chatbot backend for the Physical AI & Humanoid Robotics Textbook.

servers:
  - url: http://localhost:8000/api/v1
    description: Local development server

tags:
  - name: Auth
    description: User authentication and authorization operations
  - name: Chat
    description: Chatbot conversation and message management
  - name: Documents
    description: Document retrieval and management

paths:
  /auth/signup:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: securepassword123
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
        '400':
          description: Invalid input or user already exists

  /auth/login:
    post:
      summary: Authenticate user and get access token
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: securepassword123
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  token_type:
                    type: string
                    example: bearer
        '401':
          description: Invalid credentials

  /chat/conversations:
    get:
      summary: Get all conversations for the authenticated user
      tags: [Chat]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
    post:
      summary: Start a new conversation
      tags: [Chat]
      security:
        - bearerAuth: []
      responses:
        '201':
          description: New conversation started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

  /chat/conversations/{conversation_id}/messages:
    get:
      summary: Get messages for a specific conversation
      tags: [Chat]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: conversation_id
          schema:
            type: string
            format: uuid
          required: true
          description: ID of the conversation
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
    post:
      summary: Send a new message to a conversation
      tags: [Chat]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: conversation_id
          schema:
            type: string
            format: uuid
          required: true
          description: ID of the conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  example: "What is ROS 2?"
      responses:
        '201':
          description: Message sent and chatbot response received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '404':
          description: Conversation not found

  /documents/search:
    post:
      summary: Search for relevant documents
      tags: [Documents]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  example: "ROS 2 installation guide"
                top_k:
                  type: integer
                  format: int32
                  default: 5
                  minimum: 1
                  maximum: 10
      responses:
        '200':
          description: List of relevant documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        preferences:
          type: object
          nullable: true
        created_at:
          type: string
          format: date-time
    Conversation:
      type: object
      properties:
        conversation_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        started_at:
          type: string
          format: date-time
        last_activity_at:
          type: string
          format: date-time
    Message:
      type: object
      properties:
        message_id:
          type: string
          format: uuid
        conversation_id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
          nullable: true
        content:
          type: string
        role:
          type: string
          enum: ["user", "bot"]
        timestamp:
          type: string
          format: date-time
        retrieved_documents:
          type: array
          items:
            type: string
            format: uuid
          nullable: true
    Document:
      type: object
      properties:
        document_id:
          type: string
          format: uuid
        content:
          type: string
        embedding:
          type: array
          items:
            type: number
            format: float
        source_url:
          type: string
          format: uri
        module:
          type: string
        chapter:
          type: string
        last_updated:
          type: string
          format: date-time
