// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Module 0: Embodied Intelligence',
      items: [
        'module-0-introduction/index',
        'module-0-introduction/embodied-intelligence',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [
        'module1-ros2/introduction',
        'module1-ros2/installation',
        'module1-ros2/basic-concepts',
        'module1-ros2/nodes-topics-services',
        'module1-ros2/packages-workspaces',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo & Unity',
      items: [
        'module2-gazebo-unity/introduction',
        'module2-gazebo-unity/gazebo-basics',
        'module2-gazebo-unity/unity-integration',
        'module2-gazebo-unity/simulation-environments',
        'module2-gazebo-unity/physics-engines',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      items: [
        'module3-nvidia-isaac/introduction',
        'module3-nvidia-isaac/isaac-sdk',
        'module3-nvidia-isaac/perception-systems',
        'module3-nvidia-isaac/navigation',
        'module3-nvidia-isaac/manipulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module4-vla/introduction',
        'module4-vla/vision-systems',
        'module4-vla/language-understanding',
        'module4-vla/action-planning',
        'module4-vla/integration',
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Ethics & Safety',
      items: [
        'module-5-ethics-safety/index',
        'module-5-ethics-safety/humanoid-safety-ethics',
      ],
    },
    {
      type: 'category',
      label: 'Capstone: Autonomous Humanoid',
      items: [
        'capstone/introduction',
        'capstone/system-architecture',
        'capstone/integration',
        'capstone/testing',
        'capstone/future-directions',
      ],
    },
  ],
};

export default sidebars;
